# Generated by Django 4.2.18 on 2025-01-31 05:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='blog_url',
            field=models.CharField(db_index=True, max_length=255, unique=True),
        ),
    ]
