# Generated by Django 4.2.18 on 2025-01-31 12:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0003_category_created_at_category_updated_at'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='category',
            field=models.ManyToManyField(related_name='post_comments', to='api.category'),
        ),
    ]
